# -*- coding: utf-8 -*-
"""removebg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10oCT2LeO7CzdmqlNJEFKzP-_1HTVUnbo
"""

import streamlit as st
from rembg import remove
from PIL import Image
import io

# Streamlit app layout
st.title("Image Background Remover")
st.write("Upload an image, and this app will remove its background for you!")

# Upload image
uploaded_image = st.file_uploader("Upload your image (PNG, JPG, etc.)", type=["png", "jpg", "jpeg"])

if uploaded_image:
    # Display the uploaded image
    st.image(uploaded_image, caption="Original Image", use_column_width=True)

    # Remove background
    if st.button("Remove Background"):
        try:
            input_image = Image.open(uploaded_image)
            input_bytes = io.BytesIO()
            input_image.save(input_bytes, format="PNG")

            # Process the image
            output_bytes = remove(input_bytes.getvalue())
            output_image = Image.open(io.BytesIO(output_bytes))

            # Display the result
            st.image(output_image, caption="Image Without Background", use_column_width=True)

            # Provide a download button
            st.download_button(
                label="Download Image Without Background",
                data=output_bytes,
                file_name="output.png",
                mime="image/png",
            )

        except Exception as e:
            st.error(f"An error occurred: {e}")